### ISSUE TITLE
fixture: AttributeError: 'ManyToManyRel' object has no attribute 'contribute_to_class'

### ISSUE THREAD

**Issue by valentijnscholten** [radiac/django-tagulous#110]
I have integrated `django-tagulous` in my app and it works OK. But loading a previously fine fixture, now doesn't work anymore dure to an error related to tagulous. This fixture does not contain any tags.

serializers are setup:

```
SERIALIZATION_MODULES = {
    'xml': 'tagulous.serializers.xml_serializer',
    'json': 'tagulous.serializers.json',
    'python': 'tagulous.serializers.python',
    'yaml': 'tagulous.serializers.pyyaml',
}
```

```
uwsgi_1         | ======================================================================
uwsgi_1         | ERROR: setUpClass (dojo.unittests.test_rest_framework.UsersTest)
uwsgi_1         | ----------------------------------------------------------------------
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/serializers/json.py", line 69, in Deserializer
uwsgi_1         |     yield from PythonDeserializer(objects, **options)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/serializers/python.py", line 92, in Deserializer
uwsgi_1         |     Model = _get_model(d["model"])
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/tagulous/serializers/base.py", line 74, in _get_model
uwsgi_1         |     Model = RealModel._detag_to_serializable()
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/tagulous/models/tagged.py", line 422, in _detag_to_serializable
uwsgi_1         |     clone_field.contribute_to_class(FakeTaggedModel, field.name)
uwsgi_1         | AttributeError: 'ManyToManyRel' object has no attribute 'contribute_to_class'
uwsgi_1         | 
```

If I remove the serialization modules, the fixtures load fine. But I get the same error as in #41

**Comment by valentijnscholten** [comment]
I also note that when generating a fresh dump / fixture with `manage.py dumpdata`, the generated json is invalid and contains text about tagulous descriptors.

```
{
    "model": "dojo.product",
    "pk": 22,
    "fields": {
        "name": "Magento 1",
        "description": "shop",
        "prod_manager": "0",
        "tech_contact": "0",
        "manager": "0",
        "product_manager": null,
        "technical_contact": null,
        "team_manager": null,
        "created": null,
        "prod_type": 49,
        "updated": null,
        "tid": 0,
        "prod_numeric_grade": null,
        "business_criticality": null,
        "platform": null,
        "lifecycle": null,
        "origin": null,
        "user_records": null,
        "revenue": null,
        "external_audience": false,
        "internet_accessible": false,
        "tags_from_django_tagging": "magento, php",
        "authorized_users": [],
        "regulations": [],
        "tags": [
            "magento",
            "php"
        ]
    }
}manager.__class__: <class 'django.db.models.fields.related_descriptors.create_forward_many_to_many_manager.<locals>.ManyRelatedManager'>
,
```

**Comment by radiac** [comment]
Thanks for the report - think this should now be fixed in the develop branch:

    pip install -e git+https://github.com/radiac/django-tagulous.git@develop#egg=django-tagulous

I'll aim to release this to pypi later today or tomorrow.

**Comment by valentijnscholten** [comment]
That's the fix I also tried. But I only fixed the _detag part, so it didn't work. The fix in develop seems to work, thanks for the fast response!
