### ISSUE TITLE
running pytest failed

### ISSUE THREAD

**Issue by jedie** [radiac/django-tagulous#165]
```
django-tagulous$ pytest
Traceback (most recent call last):
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1372, in getini
    return self._inicache[name]
KeyError: 'python_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jens/toniecloud/django-tagulous/.venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 324, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/_pytest/helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1016, in pytest_cmdline_parse
    self.parse(args)
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1304, in parse
    self._preparse(args, addopts=addopts)
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1206, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/pytest_pythonpath.py", line 20, in pytest_load_initial_conftests
    for path in reversed(early_config.getini("python_paths")):
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1374, in getini
    self._inicache[name] = val = self._getini(name)
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1435, in _getini
    return self._getini_unknown_type(name, type, value)
  File "/home/jens/toniecloud/django-tagulous/.venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1381, in _getini_unknown_type
    raise ValueError(msg, value)  # pragma: no cover
ValueError: ('unknown configuration type: pathlist', '.')

```

**Comment by jedie** [comment]
https://github.com/radiac/django-tagulous/blob/1617a6286f3aea3a569a8410ef27ca908b91807f/setup.cfg#L47 must be removed.
