### ISSUE TITLE
tagulous causing: "cannot import name generic"

### ISSUE THREAD

**Issue by mitchtabian** [radiac/django-tagulous#30]
Hello,

I can't get Tagulous working on my server. After I install Tagulous (via pip) and run python manage.py makemigrations, I get this error:

**Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/tagulous/models/__init__.py", line 23, in <module>
    from tagulous.models import migrations
  File "/usr/local/lib/python2.7/dist-packages/tagulous/models/migrations.py", line 286, in <module>
    south_support()
  File "/usr/local/lib/python2.7/dist-packages/tagulous/models/migrations.py", line 199, in south_support
    from south import modelsinspector
  File "/usr/lib/python2.7/dist-packages/south/modelsinspector.py", line 20, in <module>
    from django.contrib.contenttypes import generic
ImportError: cannot import name generic**

I can't figure out why. It works on my dev server but it won't work on my Ubuntu server (digital ocean). I've attached my requirements. Also note that I've switched to django version 1.10 as it says in Tagulous documentation that is the newest supported version. Also note that I am using Python 2.7 on my Ubuntu server but using python 34 on my development server. That is the only difference I can see.

[requirements.txt](https://github.com/radiac/django-tagulous/files/1102891/requirements.txt)

**Comment by mitchtabian** [comment]
Turns out one of the files in tagulous was using django.contrib.contenttypes import generic still, I changed it to django.contrib.contenttypes import fields. My south installation was also messed up and doing the same thing. I just those and it seems to be working now.

Thanks ahead of time if you wasted any time looking into this
