### ISSUE TITLE
'list' object has no attribute 'pk'

### ISSUE THREAD

**Issue by peteyb** [radiac/django-tagulous#41]
When using with Django REST Framework 3+ and specifying the model property with `tagulous.models.TagField` a POST/PUT request via the Browsable API throws below error:

`AttributeError at /api/calendar-item/1/`
`'list' object has no attribute 'pk'`
`/usr/local/lib/python3.6/site-packages/tagulous/models/managers.py in _ensure_tags_in_db, line 522`

The DRF handles ManyToMany fields fine via API, by allowing requests to assign the related join to the entity being created/updated. 

Can you add a seralizer extension method to allow POST/PUT requests to allow posting of the multiple "tag" primary keys to be saved against related entity; instead of expecting CSV string.

**Comment by alexandrenorman** [comment]
Same issue when populating my DB from a fixture: 

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 64, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 104, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 167, in load_label
    obj.save(using=self.using)
  File "/usr/local/lib/python3.6/site-packages/django/core/serializers/base.py", line 204, in save
    getattr(self.object, accessor_name).set(object_list)
  File "/usr/local/lib/python3.6/site-packages/tagulous/models/managers.py", line 544, in set
    self.add(*objs)
  File "/usr/local/lib/python3.6/site-packages/tagulous/models/managers.py", line 584, in add
    new_tags = self._ensure_tags_in_db(new_tags)
  File "/usr/local/lib/python3.6/site-packages/tagulous/models/managers.py", line 522, in _ensure_tags_in_db
    if tag.pk:
AttributeError: Problem installing fixture '/app/django/fabrique_a_contacts/fixtures/mydump-20180219.json': 'list' object has no attribute 'pk'
```

**Comment by SuperNascher** [comment]
One of the problems can occur, if the tag field is not set  on the model and django(or django-rest-framework) emits an empty list (because of the ManyToManyField inheritance) and the add() function from the [TagRelatedManagerMixin](https://github.com/radiac/django-tagulous/blob/develop/tagulous/models/managers.py#L548) adds the list to the tags, which triggers the error on _ensure_tags_in_db().

**Comment by 4levels** [comment]
Man, this issue is so affecting me and I kept blaming Django Restframework :-(
There seems simply no way to work with tagulous and add relations in the traditional many-2-many way, by passing a list of id's.  Is there really no way to make tagulous work with simple id lists?

Hoping someone can shed some light on this

Thanks

**Comment by panpanick** [comment]
Is there still not much of a way around this? This error continues to pop up when loading a data dump.

**Comment by alex-msk** [comment]
+1

**Comment by alex-msk** [comment]
https://github.com/alex-msk/django-tagulous/commit/f69b0d2a75a8a94f90c5053c6ca179dae259e70a

I did a temporary "dirty" hack for a quick fix. Can help temporarily.

**Comment by radiac** [comment]
Firstly, apologies this has gone unanswered for so long.

This is the error you'll see if you haven't enabled the tagulous serializers in your Django settings as per the [installation instructions](http://radiac.net/projects/django-tagulous/documentation/installation/):

```
    SERIALIZATION_MODULES = {
        'xml':    'tagulous.serializers.xml_serializer',
        'json':   'tagulous.serializers.json',
        'python': 'tagulous.serializers.python',
        'yaml':   'tagulous.serializers.pyyaml',
    }
```

Although this is in the detailed installation instructions, I now realise that it's missing from the quickstart in the readme - I've updated that.

If this doesn't resolve the issue, please do re-open this.
