### ISSUE TITLE
module 'tagulous' has no attribute 'models'

### ISSUE THREAD

**Issue by rgaiacs** [radiac/django-tagulous#51]
I followed the documentation at http://radiac.net/projects/django-tagulous/documentation/usage/#example_tag_trees but

```
$ python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tagulous
>>> tagulous.__version__
'0.13.2'
>>> import lowfat.models
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/raniere/SSI/src/lowfat/lowfat/models.py", line 53, in <module>
    class FundActivity(tagulous.models.TagTreeModel):  # pylint: disable=model-no-explicit-unicode
AttributeError: module 'tagulous' has no attribute 'models'
```

**Comment by JJZolper** [comment]
I got the same thing. Running Django 2.0.5.
