### ISSUE TITLE
In admin, AttributeError: type object '<model>' has no attribute 'tag_options'

### ISSUE THREAD

**Issue by addsimm** [radiac/django-tagulous#52]
Hello

I have just installed django-tagulous and everything is working fine until I have this line:
    autocomplete_view='story_tags_autocomplete'

- I have tested it with and without running migrations on django 11

Here is my model: 

    class Story(Model):
        ...
        tags = TagField(
            autocomplete_view='story_tags_autocomplete'
        )

Here is the relevant urls.py lines:

    from tagulous.views import autocomplete
    
    url(r'^story/tags/autocomplete/', autocomplete, {'tag_model': Story}, name='story_tags_autocomplete'),

Here is a picture of what happens in the admin:

![screen shot 2018-07-31 at 10 46 08 am](https://user-images.githubusercontent.com/2389450/43477356-d1b924ae-94af-11e8-96d6-3a7b1b40d6ea.png)

Here is the traceback:

    Internal Server Error: /story/tags/autocomplete/    
    Traceback (most recent call last):
      File "/Users/adam/PycharmProjects/venv/lib/python2.7/site-packages/django/core/handlers    /exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/adam/PycharmProjects/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/adam/PycharmProjects/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/adam/PycharmProjects/venv/lib/python2.7/site-packages/tagulous/views.py", line 44, in autocomplete
    options = tag_model.tag_options
AttributeError: type object 'Story' has no attribute 'tag_options'
[31/Jul/2018 10:46:02] "GET /story/tags/autocomplete/?q=&p=1&_=1533059158650 HTTP/1.1" 500 16428

thanks

**Comment by radiac** [comment]
Hi! It looks like you're passing the tagged model - Story, the model which has been tagged - instead of the tag model, the model which stores the tags themselves. It looks like there's a mistake in the example usage documentation.

Think you're looking for:

```
url(r'^story/tags/autocomplete/', autocomplete, {'tag_model': Story.tags.tag_model}, name='story_tags_autocomplete'),
```

I'll make a note to update the documentation - thanks for letting me know!

**Comment by addsimm** [comment]
Works! Thanks
