### ISSUE TITLE
Example project doesn't run (missing migration and failed migration after making my own).

### ISSUE THREAD

**Issue by wamcvey** [radiac/django-tagulous#64]
Following the procedures associated with starting up the example project, I've run into several blocking problems.

First, to establish context that I'm starting in a clean virtualenv:

```
quantum wam-homedir:master! ~/projs $ virtualenv -p /usr/bin/python3.7 tagulous-exampleRunning virtualenv with interpreter /usr/bin/python3.7
Using base prefix '/usr'
/usr/lib/python3/dist-packages/virtualenv.py:1086: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in /home/wam/projs/tagulous-example/bin/python3.7
Also creating executable in /home/wam/projs/tagulous-example/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
quantum wam-homedir:master! ~/projs $ cd tagulous-example
/home/wam/projs/tagulous-example
quantum wam-homedir:master! ...s/tagulous-example $ source bin/activate
(tagulous-example) quantum wam-homedir:master! ...s/tagulous-example $ pip install "Django>=1.8,<1.9"
Collecting Django<1.9,>=1.8
  Downloading https://files.pythonhosted.org/packages/96/b9/b4108da1275dc2ac1bba1e87739cb31b3d44339affb83b0e949fb09c2bef/Django-1.8.19-py2.py3-none-any.whl (6.2MB)
    100% |████████████████████████████████| 6.2MB 2.4MB/s 
Installing collected packages: Django
Successfully installed Django-1.8.19
pip install -e git+https://github.com/radiac/django-tagulous.git#egg=django-tagulous
(tagulous-example) quantum wam-homedir:master! ...s/tagulous-example $ pip install -e git+https://github.com/radiac/django-tagulous.git#egg=django-tagulous
Obtaining django-tagulous from git+https://github.com/radiac/django-tagulous.git#egg=django-tagulous
  Cloning https://github.com/radiac/django-tagulous.git to ./src/django-tagulous
Installing collected packages: django-tagulous
  Running setup.py develop for django-tagulous
Successfully installed django-tagulous
(tagulous-example) quantum wam-homedir:master! ...s/tagulous-example $ cd src/django-tagulous/example
(tagulous-example) quantum django-tagulous:develop ...o-tagulous/example $ python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: messages, staticfiles, tagulous
  Apply all migrations: contenttypes, auth, admin, sessions, example
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying example.0001_initial... OK
  Applying sessions.0001_initial... OK
(tagulous-example) quantum django-tagulous:develop ...o-tagulous/example $ python manage.py createsuperuser
Username (leave blank to use 'wam'): wam
Email address: MY_EMAIL
Password: 
Password (again): 
Superuser created successfully.
```

Here's where the issues begin:
```
(tagulous-example) quantum django-tagulous:develop ...o-tagulous/example $ python manage.py initial_tags
Loading initial tags for example.Person.title
Traceback (most recent call last):
  File "/home/wam/projs/tagulous-example/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/wam/projs/tagulous-example/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: example_tagulous_person_title
```

I've deleted the longer exception because the fundamental problem is the missing table. So I figured the problem was just a missing migration that didn't get committed, so I'd recreate:

```
(tagulous-example) quantum django-tagulous:develop ...o-tagulous/example $ python manage.py makemigrations
Did you rename the example._Tagulous_Person_hobbies model to Tagulous_Person_hobbies? [y/N] y
Did you rename the example._Tagulous_Person_title model to Tagulous_Person_title? [y/N] y
Migrations for 'example':
  0002_auto_20181113_2314.py:
    - Rename model _Tagulous_Person_hobbies to Tagulous_Person_hobbies
    - Rename model _Tagulous_Person_title to Tagulous_Person_title
    - Alter field title on person
```

So far, so good:

```
(tagulous-example) quantum django-tagulous:develop ...o-tagulous/example $ python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: tagulous, messages, staticfiles
  Apply all migrations: auth, admin, contenttypes, sessions, example
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying example.0002_auto_20181113_2314...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/wam/projs/tagulous-example/lib/python3.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/wam/projs/tagulous-example/lib/python3.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/wam/projs/tagulous-example/lib/python3.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/wam/projs/tagulous-example/lib/python3.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/wam/projs/tagulous-example/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/wam/projs/tagulous-example/lib/python3.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/wam/projs/tagulous-example/lib/python3.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/wam/projs/tagulous-example/lib/python3.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/wam/projs/tagulous-example/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 201, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/wam/projs/tagulous-example/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 484, in alter_field
    old_db_params, new_db_params, strict)
  File "/home/wam/projs/tagulous-example/lib/python3.7/site-packages/django/db/backends/sqlite3/schema.py", line 203, in _alter_field
    self._remake_table(model, alter_fields=[(old_field, new_field)])
  File "/home/wam/projs/tagulous-example/lib/python3.7/site-packages/django/db/backends/sqlite3/schema.py", line 140, in _remake_table
    self.create_model(temp_model)
  File "/home/wam/projs/tagulous-example/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 250, in create_model
    to_table = field.rel.to._meta.db_table
AttributeError: 'str' object has no attribute '_meta'
(1)
```

And it's all gone to crap. Keep in mind, this is the example project, using the build procedure specified in the documentation at: https://github.com/radiac/django-tagulous/tree/master/example

**Comment by radiac** [comment]
Thanks for letting me know - looks like I forgot to apply the upgrade instructions to it. Will take a look at upgrading it to 1.11 at some point soon.
