### ISSUE TITLE
ImportError: cannot import name 'generic' from 'django.contrib.contenttypes'

### ISSUE THREAD

**Issue by djjudas21** [radiac/django-tagulous#86]
Hi there. I've just added a basic installation of Tagulous as follows:

```
(venv) [jonathan@latitude camerahub]$ git diff master..284_tags
diff --git a/camerahub/settings.py b/camerahub/settings.py
index c3382f5..4e9171d 100644
--- a/camerahub/settings.py
+++ b/camerahub/settings.py
@@ -50,6 +50,7 @@ INSTALLED_APPS = [
     'moderation',
     'fullurl',
     'django_filters',
+    'tagulous',
     'watson',
 ]
 
diff --git a/requirements.txt b/requirements.txt
index 6178b31..12f9c1b 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -19,6 +19,7 @@ django-moderation>=0.7.0,<1.0.0
 django-fullurl>=1.0,<2.0
 django-filter>=2.2.0,<3.0.0
 awesome-slugify>=1.6.5,<2.0.0
+django-tagulous>=0.14.1,<1.0.0
 django-watson>=1.5.5,<2.0.0
 django-redis>=4.11.0,<5.0.0
diff --git a/schema/models.py b/schema/models.py
index 4a956cc..c21e1de 100644
--- a/schema/models.py
+++ b/schema/models.py
@@ -10,6 +10,7 @@ from djchoices import DjangoChoices, ChoiceItem
 from django_currentuser.db.models import CurrentUserField
 from autosequence.fields import AutoSequenceField
 from slugify import Slugify, UniqueSlugify
+import tagulous.models
 
 
 def cameramodel_check(text, uids):
@@ -1322,6 +1323,7 @@ class CameraModel(models.Model):
     updated_at = models.DateTimeField(auto_now=True, null=True, editable=False)
     updated_by = CurrentUserField(
         on_update=True, editable=False, related_name='cameramodel_updated_by')
+    tags = tagulous.models.TagField()
 
     # Fixed lens fields
     lens_manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE,
```

Unfortunately I'm running into this error when I try to start up:

```
(venv) [jonathan@latitude camerahub]$ python manage.py runserver
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jonathan/.local/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/jonathan/.local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/jonathan/.local/lib/python3.7/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[0](_exception[1]).with_traceback(_exception[2])
  File "/home/jonathan/.local/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/jonathan/.local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jonathan/.local/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/jonathan/.local/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jonathan/git/camerahub/schema/models.py", line 13, in <module>
    import tagulous.models
  File "/home/jonathan/.local/lib/python3.7/site-packages/tagulous/models/__init__.py", line 23, in <module>
    from tagulous.models import migrations
  File "/home/jonathan/.local/lib/python3.7/site-packages/tagulous/models/migrations.py", line 286, in <module>
    south_support()
  File "/home/jonathan/.local/lib/python3.7/site-packages/tagulous/models/migrations.py", line 199, in south_support
    from south import modelsinspector
  File "/home/jonathan/.local/lib/python3.7/site-packages/south/modelsinspector.py", line 20, in <module>
    from django.contrib.contenttypes import generic
ImportError: cannot import name 'generic' from 'django.contrib.contenttypes' (/home/jonathan/.local/lib/python3.7/site-packages/django/contrib/contenttypes/__init__.py)
```

Looks like the same bug as this - https://stackoverflow.com/questions/35454154/importerror-cannot-import-name-generic/35454302

**Comment by radiac** [comment]
Hi! It looks like you've got South installed, which means Tagulous tries to add support for tag fields using `south.modelinspector`. However, South does not work Django >= 1.9, so the error is coming when that South module is imported.

There hasn't really been a reason to use South in a project since Django 1.7 introduced native migrations. 1.7 reached its end of life in Dec 2015 when 1.9 was released, which was South's last release date too. The project is dead; Tagulous will therefore soon* drop support for it, which would resolve this issue, but I strongly recommend removing South from your project regardless, along with any stale project which marks it as a dependency.

Try using [pipdeptree](https://pypi.org/project/pipdeptree/) to see why South is being installed. (Also I'd recommend using [pip-tools](https://pypi.org/project/pip-tools/), which makes managing packages and tracing dependencies much easier).

Hope this helps!

* soon as in versions - unfortunately current circumstances mean I can't predict actual release dates.
