### ISSUE TITLE
NoReverseMatch when trying to return parent path in get_absolute_url

### ISSUE THREAD

**Issue by 11NightHawk** [radiac/django-tagulous#94]
This is my `get_absolute_url` in a custom `TagTreeModel` in `models.py:`

```
def get_absolute_url(self):
    return reverse('WorkNukeSkill:by_skill', kwargs={'skill_path': self.path})
```

`urls.py`:

```
urlpatterns = [
    path('browse/tag/<skill_path>/', views.by_skill, name='by_skill'),
]
```

`views.py`:

```
def by_skill(request, skill_path):
    tag = get_object_or_404(Skill, path=skill_path)
    my_qs = JobPost.objects.filter(jobskill=tag)
    context = {
        'tag': tag,
        'job_list': my_qs,
    }
    return render(request, 'user_home.html', context)
```

It works perfectly fine when tags don't have parents. This is the error I get the moment I add a parent tag and a child to the database:

**NoReverseMatch at /browse/
Reverse for 'by_skill' with keyword arguments '{'skill_path': 'javascript/jquery'}' not found. 1 pattern(s) tried: ['browse/tag/(?P<skill_path>[^/]+)/$']**

```
Traceback (most recent call last):
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "A:\WNProject\src\worknuke\JobPosts\views.py", line 22, in job_post_list_view
    return render(request, template_name, context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 986, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 670, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 795, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\template\base.py", line 857, in _resolve_lookup
    current = current()
  File "A:\WNProject\src\worknuke\SkillList\models.py", line 21, in get_absolute_url
    return reverse('WorkNukeSkill:by_skill', kwargs={'skill_path': self.path})
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\11NytHwk\.virtualenvs\WNProject-_FoVTRtw\lib\site-packages\django\urls\resolvers.py", line 676, in _reverse_with_prefix
    raise NoReverseMatch(msg)

Exception Type: NoReverseMatch at /browse/
Exception Value: Reverse for 'by_skill' with keyword arguments '{'skill_path': 'javascript/jquery'}' not found. 1 pattern(s) tried: ['browse/tag/(?P<skill_path>[^/]+)/$']
```

**Comment by radiac** [comment]
Tags with parents have a /, so you need something like

re_path('^browse/tag/(?P<skill_path>.+)/', ...

**Comment by 11NightHawk** [comment]
Hey! thanks for that! Do you know how I can get the child objects to display as well when I just select the parent object in the url?
Right now, I have a parent tag `Python` on one post and a child tag `Django` set to another. When the user selects `Python `as a tag filter, I want the `Django` post to also show up since it's a child tag.

Any help would be greatly appreciated!

**Comment by radiac** [comment]
No problem. You could just use multiple tags - ie tag it with both `Python` and `Python/Django` to have it show in both, but because a tag field is a standard m2m relationship, you could do something like
```
    my_qs = JobPost.objects.filter(jobskill__startswith=tag)
```
to collect all descendants. Note that because there's no trailing slash that would also catch a `Python snakes` tag, so you probably would want to OR your original filter with a startswith using a trailing slash, eg
```
    my_qs = JobPost.objects.filter(Q(jobskill=tag) | Q(jobskill__startswith=f"{tag}/"))
```
Untested, but hope that points you in the right direction!

**Comment by 11NightHawk** [comment]
I see, I hadn't thought of something like that. I was wondering if your suggestion was gonna be something something related to `get_decendents` or `get_siblings`. I tried what you suggested and it gave me this error: `Related Field got invalid lookup: startswith`

**Comment by radiac** [comment]
You could use those methods, but it may result in more db queries.

Ah of course - try `jobskill__name__startswith`?

**Comment by 11NightHawk** [comment]
That works great, but the only issue is if the post has two tags of the same parent, then that post is printed out twice

**Comment by radiac** [comment]
Could try adding `.distinct()` after the filter?

**Comment by 11NightHawk** [comment]
Thanks so much! Trying to get into django and you helped out a lot! I appreciate it :)

**Comment by radiac** [comment]
Brilliant, glad I could help!
