### ISSUE TITLE
Error when running Fixture: no such table: tagulous_faketaggedmodel

### ISSUE THREAD

**Issue by Rohail1** [radiac/django-tagulous#98]
I am using Django 2.2. and django-tagulous 0.14.1.  Following are my model structure 

```
class Categories(tagulous.models.TagTreeModel):
    class Meta:
        verbose_name_plural = "categories"

    class TagMeta:
        initial = ['wedding', 'engagement', 'bridal shower', 'bar mitzvah',
                   'bat mitzvah', 'baby boy', 'baby girl', 'graduation',
                   'birthday', 'birthday/kids', 'birthday/kids/boy', 'birthday/kids/girl',
                   'birthday/adult', 'birthday/adult/man', 'birthday/adult/woman']
        force_lowercase = True
        protect_all = True


```

```
class Template(models.Model):
    published = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=150, null=False)
    style = models.CharField(max_length=150, null=True, blank=True)
    owner = models.ForeignKey('core.User', related_name='templates', on_delete=models.SET_NULL, null=True)
    categories = tagulous.models.TagField(to=Categories)
```

Now when I run the loaddata command to run the fixture I get the following error.

```
python manage.py loaddata seed-data/new_templates.json
Traceback (most recent call last):
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: tagulous_faketaggedmodel

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: tagulous_faketaggedmodel

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 114, in loaddata
    self.load_label(fixture_label)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 180, in load_label
    obj.save(using=self.using)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/core/serializers/base.py", line 224, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/models/base.py", line 851, in _save_table
    forced_update)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/models/base.py", line 900, in _do_update
    return filtered._update(values) > 0
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/models/query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1426, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1097, in execute_sql
    cursor.execute(sql, params)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 103, in execute
    sql = self.db.ops.last_executed_query(self.cursor, sql, params)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/operations.py", line 150, in last_executed_query
    params = self._quote_params_for_last_executed_query(params)
  File "/Users/rohailnajam/Projects/birdie/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/operations.py", line 139, in _quote_params_for_last_executed_query
    return cursor.execute(sql, params).fetchone()
sqlite3.InterfaceError: Problem installing fixture '/Users/rohailnajam/Projects/birdie/seed-data/new_templates.json': Error binding parameter 5 - probably unsupported type.

```

Here is the data in my fixture file

```
[
  {
    "model": "templates.template",
    "pk": 1,
    "fields": {
      "published": false,
      "created": "2019-11-15T18:30:21.648Z",
      "name": "Dashing Birthday",
      "style": "STYLE",
      "owner": 1,
      "categories": ["Wedding"]
    }
  }
]
```

**Comment by Rohail1** [comment]
@radiac Can you tell me what is the issue and how to fix it?

**Comment by radiac** [comment]
Sorry, missed this when it came in - do you have the following in your settings?

```
SERIALIZATION_MODULES = {
    'xml':    'tagulous.serializers.xml_serializer',
    'json':   'tagulous.serializers.json',
    'python': 'tagulous.serializers.python',
    'yaml':   'tagulous.serializers.pyyaml',
}
```

**Comment by Rohail1** [comment]
Yes. I do. It works perfectly in other scenarios. It only crashes during the Django loaddata command

**Comment by radiac** [comment]
I've been testing this and think it should now be resolved in the latest Tagulous. Do reopen if you still have problems.
